# Generated by Django 4.2.1 on 2023-05-15 13:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_text', models.CharField(max_length=300)),
                ('pub_date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
