# Generated by Django 3.1.6 on 2023-05-16 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postrequirement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
